# Generated by Django 5.0.3 on 2024-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reg',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='reg',
            name='mail',
            field=models.CharField(blank=True, max_length=30, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='reg',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reg',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамиялия'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='login',
            field=models.CharField(max_length=30, verbose_name='Логин'),
        ),
    ]
